security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }

        member_db:
            entity:
                class: App\Entity\Member

    role_hierarchy:
        # ADVERT_EDITOR can edit any advert
        # ADVERT_DELETOR can delete any advert
        ROLE_ADMIN: [ROLE_ADVERT_DELETOR, ROLE_ADVERT_EDITOR]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: member_db

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: app_security.login
                check_path: app_security.login
                default_target_path: app_users.home

                csrf_token_generator: security.csrf.token_manager

            logout:
                path: app_security.logout
                target: app_core.home

            guard:
                authenticators:
                    - App\Security\FacebookAuthenticator
                provider: member_db

    access_control:
        - { path: /users/login$, roles: IS_AUTHENTICATES_ANONYMOUSLY }
        - { path: /users/(?!(login|signup))$, roles: ROLE_USER }
        - { path: /adverts/(!(search))$, roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        App\Entity\Member: bcrypt
