<?php

namespace App\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository as EntityRepository;

/**
 * FacebookMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookMemberRepository extends EntityRepository implements UserLoaderInterface
{
	public function loadUserByUsername($username)
	{
		return $this->createQueryBuilder('m')
			->where('m.username = :username OR m.facebookId = :id')
			->setParameter('username', $username)
			->setParameter('id', $username)
			->getQuery()
			->getOneOrNullResult();
	}
}
