<?php

namespace App\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository as EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository implements UserLoaderInterface
{
	public function loadUserByUsername($username)
	{
		return $this->createQueryBuilder('m')
			->where('m.username = :username OR m.mail = :mail')
			->setParameter('username', $username)
			->setParameter('mail', strtolower($username))
			->getQuery()
			->getOneOrNullResult();
	}
}
