app:
    resource: 'routes/translatable.yaml'
    prefix: '/{_locale}'

home:
    path: '/'
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true
